trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: Install tools

- script: pip install pydocstyle flake8 black
  displayName: Install dependencies

- script: black --check .
  displayName: Run Black checks

- script: flake8 .
  displayName: Run flake8 checks

- script: pydocstyle .
  displayName: Verify docstings
